"""empty message

Revision ID: 06e9f56a60c9
Revises: 2e14f865dc19
Create Date: 2021-11-13 13:29:16.922528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06e9f56a60c9'
down_revision = '2e14f865dc19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservation', sa.Column('price', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservation', 'price')
    # ### end Alembic commands ###
