"""empty message

Revision ID: 2e14f865dc19
Revises: 386f52b1037a
Create Date: 2021-11-08 23:18:02.721017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e14f865dc19'
down_revision = '386f52b1037a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event', 'superadmin_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event', 'superadmin_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
