"""empty message

Revision ID: 697ce309663a
Revises: 06e9f56a60c9
Create Date: 2021-11-13 13:44:42.919515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '697ce309663a'
down_revision = '06e9f56a60c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('reservation_event_id_fkey', 'reservation', type_='foreignkey')
    op.drop_constraint('reservation_superadmin_id_fkey', 'reservation', type_='foreignkey')
    op.drop_column('reservation', 'event_id')
    op.drop_column('reservation', 'superadmin_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservation', sa.Column('superadmin_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('reservation', sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('reservation_superadmin_id_fkey', 'reservation', 'superadmin', ['superadmin_id'], ['id'])
    op.create_foreign_key('reservation_event_id_fkey', 'reservation', 'event', ['event_id'], ['id'])
    # ### end Alembic commands ###
